// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBv_XEcyGUpvK4WiBkoLKqvHPMPXV6T_9U',
    appId: '1:159430048573:web:e783c3cc87d5620b482354',
    messagingSenderId: '159430048573',
    projectId: 'rotauni-117ad',
    authDomain: 'rotauni-117ad.firebaseapp.com',
    storageBucket: 'rotauni-117ad.firebasestorage.app',
    measurementId: 'G-7C3H2FBGMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYxjYaMDe2Ot4kv3rLWxaDQJ1ChPQEmfw',
    appId: '1:159430048573:android:a3d5b523fe1bb2d7482354',
    messagingSenderId: '159430048573',
    projectId: 'rotauni-117ad',
    storageBucket: 'rotauni-117ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxgnNH91XkD5TbIyRw1Dk7oczn-Ecl9fA',
    appId: '1:159430048573:ios:bfbf20321aa47460482354',
    messagingSenderId: '159430048573',
    projectId: 'rotauni-117ad',
    storageBucket: 'rotauni-117ad.firebasestorage.app',
    iosBundleId: 'com.example.appRotauni',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxgnNH91XkD5TbIyRw1Dk7oczn-Ecl9fA',
    appId: '1:159430048573:ios:bfbf20321aa47460482354',
    messagingSenderId: '159430048573',
    projectId: 'rotauni-117ad',
    storageBucket: 'rotauni-117ad.firebasestorage.app',
    iosBundleId: 'com.example.appRotauni',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBv_XEcyGUpvK4WiBkoLKqvHPMPXV6T_9U',
    appId: '1:159430048573:web:60619200ae71c673482354',
    messagingSenderId: '159430048573',
    projectId: 'rotauni-117ad',
    authDomain: 'rotauni-117ad.firebaseapp.com',
    storageBucket: 'rotauni-117ad.firebasestorage.app',
    measurementId: 'G-X8HQS6EZ5R',
  );
}
